// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/category_model/category_model.dart';
import 'model/customer_model/customer_model.dart';
import 'model/order_model/order_model.dart';
import 'model/product_model/product_model.dart';
import 'model/supplier_model/supplier_model.dart';
import 'model/unit_model/unit_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8462100601893205612),
      name: 'OrderModel',
      lastPropertyId: const obx_int.IdUid(11, 4254633851667221722),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8479132576122394026),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4523916266304147786),
            name: 'thoi_gian_mua',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3335041921269555226),
            name: 'uid_khach_hang',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1856729103606736230),
            name: 'ten_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2970767064493836545),
            name: 'hinh_khach_hang',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6596033124175339077),
            name: 'sdt_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7967327727288773898),
            name: 'khach_no',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3362299750829196582),
            name: 'tong_tien_no',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2750023190832166596),
            name: 'tong_gia',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4944268585478704077),
            name: 'createDate',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4254633851667221722),
            name: 'customerId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 5774386875927907610),
            relationTarget: 'CustomerModel')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 6117545004750295902),
            name: 'list_product',
            targetId: const obx_int.IdUid(4, 3376631319514457996))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 2774907212245098214),
      name: 'PriceList',
      lastPropertyId: const obx_int.IdUid(9, 2986229849620795832),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1657564179567643833),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7220771278987625304),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6753043266397354163),
            name: 'gia_ban',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1009228909912017167),
            name: 'so_luong',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2986229849620795832),
            name: 'unitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 573286813381815073),
            relationTarget: 'UnitModel')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3376631319514457996),
      name: 'ProductItem',
      lastPropertyId: const obx_int.IdUid(18, 7225780580063542658),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8241860205670702977),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 812030874404062344),
            name: 'uid_product',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8566887608838875456),
            name: 'barcode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7823422843550329682),
            name: 'ten_san_pham',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7405349370863855049),
            name: 'hinh_san_pham',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4278042561808483539),
            name: 'so_luong',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 570108286703470966),
            name: 'supplierId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 5865870161720845457),
            relationTarget: 'SupplierModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 4560353825386576500),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 2130917950542592992),
            relationTarget: 'CategoryModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 4894164430705184576),
            name: 'unitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 698629806240375668),
            relationTarget: 'UnitModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 7225780580063542658),
            name: 'priceId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(7, 525945562797319887),
            relationTarget: 'PriceList')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 2699875232035799149),
      name: 'ProductModel',
      lastPropertyId: const obx_int.IdUid(16, 7855610327950231430),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5571371203571454592),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9008781066506134880),
            name: 'barcode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5009954247164826755),
            name: 'ten_san_pham',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6061245436868486034),
            name: 'hinh_san_pham',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6021767469518361791),
            name: 'ghi_chu',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6807131810671397937),
            name: 'gia_nhap',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6214602939360826599),
            name: 'dung_tich',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6850306170653725048),
            name: 'so_luong',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5625414788275987508),
            name: 'supplierId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(8, 8124704708369060400),
            relationTarget: 'SupplierModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 6536713529042721626),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(9, 405308505056760631),
            relationTarget: 'CategoryModel'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 7855610327950231430),
            name: 'unitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(10, 5042270014188455772),
            relationTarget: 'UnitModel')
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 7058649337610862334),
            name: 'price_list',
            targetId: const obx_int.IdUid(3, 2774907212245098214))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 4395494203919008109),
      name: 'UnitModel',
      lastPropertyId: const obx_int.IdUid(5, 7563155607688441043),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5938035661955631924),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3111332530529794604),
            name: 'ten_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8792214140384089297),
            name: 'loai_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2015183802015280897),
            name: 'ky_hieu',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 3646208378886933205),
      name: 'CustomerModel',
      lastPropertyId: const obx_int.IdUid(6, 6050084833291723297),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3579513034822440326),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3157431911059337559),
            name: 'ten_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5664871943150517921),
            name: 'hinh_khach_hang',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7109396362435822095),
            name: 'sdt_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9038904169819601270),
            name: 'dia_chi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6050084833291723297),
            name: 'createDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 3828381250875953042),
      name: 'CategoryModel',
      lastPropertyId: const obx_int.IdUid(4, 5633756422000733903),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2944983431183764254),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6201877116637760197),
            name: 'ten_danh_muc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4835612102365298861),
            name: 'loai_danh_muc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5633756422000733903),
            name: 'createDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 4684840811247125917),
      name: 'SupplierModel',
      lastPropertyId: const obx_int.IdUid(4, 1856481308765661819),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1940646799049802203),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6228732961812636152),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5012052220393829989),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1856481308765661819),
            name: 'phone',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(9, 4684840811247125917),
      lastIndexId: const obx_int.IdUid(10, 5042270014188455772),
      lastRelationId: const obx_int.IdUid(2, 6117545004750295902),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [4121840046154517435],
      retiredIndexUids: const [681671148803372239],
      retiredPropertyUids: const [
        2554028156081344597,
        3276445162843721571,
        1946115600899689025,
        8241427837389614950,
        8090806262661001619,
        6837452732912493970,
        7032831974186877870,
        4266610608789417277,
        6931669776031782900,
        2994713848890333595,
        5424488080241102282,
        8326155832968762877,
        7410578384373947376,
        4117038924924385776,
        8744451219592071,
        8312112673082639836,
        7229928441048565709,
        1518545134613383641,
        6982042452188979866,
        6001654584984488585,
        883625706046727771,
        7563155607688441043
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    OrderModel: obx_int.EntityDefinition<OrderModel>(
        model: _entities[0],
        toOneRelations: (OrderModel object) => [object.customer],
        toManyRelations: (OrderModel object) => {
              obx_int.RelInfo<OrderModel>.toMany(2, object.uid):
                  object.list_product
            },
        getId: (OrderModel object) => object.uid,
        setId: (OrderModel object, int id) {
          object.uid = id;
        },
        objectToFB: (OrderModel object, fb.Builder fbb) {
          final ten_khach_hangOffset = object.ten_khach_hang == null
              ? null
              : fbb.writeString(object.ten_khach_hang!);
          final hinh_khach_hangOffset = object.hinh_khach_hang == null
              ? null
              : fbb.writeListInt8(object.hinh_khach_hang!);
          final sdt_khach_hangOffset = object.sdt_khach_hang == null
              ? null
              : fbb.writeString(object.sdt_khach_hang!);
          fbb.startTable(12);
          fbb.addInt64(0, object.uid);
          fbb.addInt64(1, object.thoi_gian_mua?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.uid_khach_hang);
          fbb.addOffset(3, ten_khach_hangOffset);
          fbb.addOffset(4, hinh_khach_hangOffset);
          fbb.addOffset(5, sdt_khach_hangOffset);
          fbb.addBool(6, object.khach_no);
          fbb.addFloat64(7, object.tong_tien_no);
          fbb.addFloat64(8, object.tong_gia);
          fbb.addInt64(9, object.createDate?.millisecondsSinceEpoch);
          fbb.addInt64(10, object.customer.targetId);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final thoi_gian_muaValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final thoi_gian_muaParam = thoi_gian_muaValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(thoi_gian_muaValue);
          final uid_khach_hangParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final ten_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final hinh_khach_hangParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 12) as Uint8List?;
          final sdt_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final khach_noParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final tong_tien_noParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final tong_giaParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = OrderModel(
              uid: uidParam,
              thoi_gian_mua: thoi_gian_muaParam,
              uid_khach_hang: uid_khach_hangParam,
              ten_khach_hang: ten_khach_hangParam,
              hinh_khach_hang: hinh_khach_hangParam,
              sdt_khach_hang: sdt_khach_hangParam,
              khach_no: khach_noParam,
              tong_tien_no: tong_tien_noParam,
              tong_gia: tong_giaParam,
              createDate: createDateParam);
          object.customer.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          object.customer.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<OrderModel>(
              object.list_product,
              store,
              obx_int.RelInfo<OrderModel>.toMany(2, object.uid));
          return object;
        }),
    PriceList: obx_int.EntityDefinition<PriceList>(
        model: _entities[1],
        toOneRelations: (PriceList object) => [object.unit],
        toManyRelations: (PriceList object) => {},
        getId: (PriceList object) => object.uid,
        setId: (PriceList object, int id) {
          object.uid = id;
        },
        objectToFB: (PriceList object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(10);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, nameOffset);
          fbb.addFloat64(5, object.gia_ban);
          fbb.addInt64(6, object.so_luong);
          fbb.addInt64(8, object.unit.targetId);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final gia_banParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final so_luongParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = PriceList(
              uid: uidParam,
              name: nameParam,
              gia_ban: gia_banParam,
              so_luong: so_luongParam);
          object.unit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.unit.attach(store);
          return object;
        }),
    ProductItem: obx_int.EntityDefinition<ProductItem>(
        model: _entities[2],
        toOneRelations: (ProductItem object) =>
            [object.supplier, object.category, object.unit, object.price],
        toManyRelations: (ProductItem object) => {},
        getId: (ProductItem object) => object.uid,
        setId: (ProductItem object, int id) {
          object.uid = id;
        },
        objectToFB: (ProductItem object, fb.Builder fbb) {
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final ten_san_phamOffset = object.ten_san_pham == null
              ? null
              : fbb.writeString(object.ten_san_pham!);
          final hinh_san_phamOffset = object.hinh_san_pham == null
              ? null
              : fbb.writeListInt8(object.hinh_san_pham!);
          fbb.startTable(19);
          fbb.addInt64(0, object.uid);
          fbb.addInt64(1, object.uid_product);
          fbb.addOffset(2, barcodeOffset);
          fbb.addOffset(3, ten_san_phamOffset);
          fbb.addOffset(4, hinh_san_phamOffset);
          fbb.addInt64(13, object.so_luong);
          fbb.addInt64(14, object.supplier.targetId);
          fbb.addInt64(15, object.category.targetId);
          fbb.addInt64(16, object.unit.targetId);
          fbb.addInt64(17, object.price.targetId);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uid_productParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final ten_san_phamParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final hinh_san_phamParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 12) as Uint8List?;
          final so_luongParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          final object = ProductItem(
              uid: uidParam,
              uid_product: uid_productParam,
              barcode: barcodeParam,
              ten_san_pham: ten_san_phamParam,
              hinh_san_pham: hinh_san_phamParam,
              so_luong: so_luongParam);
          object.supplier.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          object.supplier.attach(store);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0);
          object.category.attach(store);
          object.unit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          object.unit.attach(store);
          object.price.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 38, 0);
          object.price.attach(store);
          return object;
        }),
    ProductModel: obx_int.EntityDefinition<ProductModel>(
        model: _entities[3],
        toOneRelations: (ProductModel object) =>
            [object.supplier, object.category, object.unit],
        toManyRelations: (ProductModel object) => {
              obx_int.RelInfo<ProductModel>.toMany(1, object.uid):
                  object.price_list
            },
        getId: (ProductModel object) => object.uid,
        setId: (ProductModel object, int id) {
          object.uid = id;
        },
        objectToFB: (ProductModel object, fb.Builder fbb) {
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final ten_san_phamOffset = object.ten_san_pham == null
              ? null
              : fbb.writeString(object.ten_san_pham!);
          final hinh_san_phamOffset = object.hinh_san_pham == null
              ? null
              : fbb.writeListInt8(object.hinh_san_pham!);
          final ghi_chuOffset =
              object.ghi_chu == null ? null : fbb.writeString(object.ghi_chu!);
          fbb.startTable(17);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, barcodeOffset);
          fbb.addOffset(2, ten_san_phamOffset);
          fbb.addOffset(3, hinh_san_phamOffset);
          fbb.addOffset(9, ghi_chuOffset);
          fbb.addFloat64(10, object.gia_nhap);
          fbb.addInt64(11, object.dung_tich);
          fbb.addInt64(12, object.so_luong);
          fbb.addInt64(13, object.supplier.targetId);
          fbb.addInt64(14, object.category.targetId);
          fbb.addInt64(15, object.unit.targetId);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final ten_san_phamParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final hinh_san_phamParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 10) as Uint8List?;
          final ghi_chuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final gia_nhapParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final dung_tichParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final so_luongParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final object = ProductModel(
              uid: uidParam,
              barcode: barcodeParam,
              ten_san_pham: ten_san_phamParam,
              hinh_san_pham: hinh_san_phamParam,
              ghi_chu: ghi_chuParam,
              gia_nhap: gia_nhapParam,
              dung_tich: dung_tichParam,
              so_luong: so_luongParam);
          object.supplier.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          object.supplier.attach(store);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          object.category.attach(store);
          object.unit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 34, 0);
          object.unit.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<ProductModel>(
              object.price_list,
              store,
              obx_int.RelInfo<ProductModel>.toMany(1, object.uid));
          return object;
        }),
    UnitModel: obx_int.EntityDefinition<UnitModel>(
        model: _entities[4],
        toOneRelations: (UnitModel object) => [],
        toManyRelations: (UnitModel object) => {},
        getId: (UnitModel object) => object.uid,
        setId: (UnitModel object, int id) {
          object.uid = id;
        },
        objectToFB: (UnitModel object, fb.Builder fbb) {
          final ten_don_viOffset = object.ten_don_vi == null
              ? null
              : fbb.writeString(object.ten_don_vi!);
          final loai_don_viOffset = object.loai_don_vi == null
              ? null
              : fbb.writeString(object.loai_don_vi!);
          final ky_hieuOffset =
              object.ky_hieu == null ? null : fbb.writeString(object.ky_hieu!);
          fbb.startTable(6);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, ten_don_viOffset);
          fbb.addOffset(2, loai_don_viOffset);
          fbb.addOffset(3, ky_hieuOffset);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final ten_don_viParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final loai_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final ky_hieuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = UnitModel(
              uid: uidParam,
              ten_don_vi: ten_don_viParam,
              loai_don_vi: loai_don_viParam,
              ky_hieu: ky_hieuParam);

          return object;
        }),
    CustomerModel: obx_int.EntityDefinition<CustomerModel>(
        model: _entities[5],
        toOneRelations: (CustomerModel object) => [],
        toManyRelations: (CustomerModel object) => {},
        getId: (CustomerModel object) => object.uid,
        setId: (CustomerModel object, int id) {
          object.uid = id;
        },
        objectToFB: (CustomerModel object, fb.Builder fbb) {
          final ten_khach_hangOffset = object.ten_khach_hang == null
              ? null
              : fbb.writeString(object.ten_khach_hang!);
          final hinh_khach_hangOffset = object.hinh_khach_hang == null
              ? null
              : fbb.writeListInt8(object.hinh_khach_hang!);
          final sdt_khach_hangOffset = object.sdt_khach_hang == null
              ? null
              : fbb.writeString(object.sdt_khach_hang!);
          final dia_chiOffset =
              object.dia_chi == null ? null : fbb.writeString(object.dia_chi!);
          fbb.startTable(7);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, ten_khach_hangOffset);
          fbb.addOffset(2, hinh_khach_hangOffset);
          fbb.addOffset(3, sdt_khach_hangOffset);
          fbb.addOffset(4, dia_chiOffset);
          fbb.addInt64(5, object.createDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final ten_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final hinh_khach_hangParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 8) as Uint8List?;
          final sdt_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final dia_chiParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = CustomerModel(
              uid: uidParam,
              ten_khach_hang: ten_khach_hangParam,
              hinh_khach_hang: hinh_khach_hangParam,
              sdt_khach_hang: sdt_khach_hangParam,
              dia_chi: dia_chiParam,
              createDate: createDateParam);

          return object;
        }),
    CategoryModel: obx_int.EntityDefinition<CategoryModel>(
        model: _entities[6],
        toOneRelations: (CategoryModel object) => [],
        toManyRelations: (CategoryModel object) => {},
        getId: (CategoryModel object) => object.uid,
        setId: (CategoryModel object, int id) {
          object.uid = id;
        },
        objectToFB: (CategoryModel object, fb.Builder fbb) {
          final ten_danh_mucOffset = object.ten_danh_muc == null
              ? null
              : fbb.writeString(object.ten_danh_muc!);
          final loai_danh_mucOffset = object.loai_danh_muc == null
              ? null
              : fbb.writeString(object.loai_danh_muc!);
          fbb.startTable(5);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, ten_danh_mucOffset);
          fbb.addOffset(2, loai_danh_mucOffset);
          fbb.addInt64(3, object.createDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final ten_danh_mucParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final loai_danh_mucParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = CategoryModel(
              uid: uidParam,
              ten_danh_muc: ten_danh_mucParam,
              loai_danh_muc: loai_danh_mucParam,
              createDate: createDateParam);

          return object;
        }),
    SupplierModel: obx_int.EntityDefinition<SupplierModel>(
        model: _entities[7],
        toOneRelations: (SupplierModel object) => [],
        toManyRelations: (SupplierModel object) => {},
        getId: (SupplierModel object) => object.uid,
        setId: (SupplierModel object, int id) {
          object.uid = id;
        },
        objectToFB: (SupplierModel object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final addressOffset =
              object.address == null ? null : fbb.writeString(object.address!);
          final phoneOffset =
              object.phone == null ? null : fbb.writeString(object.phone!);
          fbb.startTable(5);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, addressOffset);
          fbb.addOffset(3, phoneOffset);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final addressParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = SupplierModel(
              uid: uidParam,
              name: nameParam,
              address: addressParam,
              phone: phoneParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OrderModel] entity fields to define ObjectBox queries.
class OrderModel_ {
  /// See [OrderModel.uid].
  static final uid =
      obx.QueryIntegerProperty<OrderModel>(_entities[0].properties[0]);

  /// See [OrderModel.thoi_gian_mua].
  static final thoi_gian_mua =
      obx.QueryDateProperty<OrderModel>(_entities[0].properties[1]);

  /// See [OrderModel.uid_khach_hang].
  static final uid_khach_hang =
      obx.QueryIntegerProperty<OrderModel>(_entities[0].properties[2]);

  /// See [OrderModel.ten_khach_hang].
  static final ten_khach_hang =
      obx.QueryStringProperty<OrderModel>(_entities[0].properties[3]);

  /// See [OrderModel.hinh_khach_hang].
  static final hinh_khach_hang =
      obx.QueryByteVectorProperty<OrderModel>(_entities[0].properties[4]);

  /// See [OrderModel.sdt_khach_hang].
  static final sdt_khach_hang =
      obx.QueryStringProperty<OrderModel>(_entities[0].properties[5]);

  /// See [OrderModel.khach_no].
  static final khach_no =
      obx.QueryBooleanProperty<OrderModel>(_entities[0].properties[6]);

  /// See [OrderModel.tong_tien_no].
  static final tong_tien_no =
      obx.QueryDoubleProperty<OrderModel>(_entities[0].properties[7]);

  /// See [OrderModel.tong_gia].
  static final tong_gia =
      obx.QueryDoubleProperty<OrderModel>(_entities[0].properties[8]);

  /// See [OrderModel.createDate].
  static final createDate =
      obx.QueryDateProperty<OrderModel>(_entities[0].properties[9]);

  /// See [OrderModel.customer].
  static final customer = obx.QueryRelationToOne<OrderModel, CustomerModel>(
      _entities[0].properties[10]);

  /// see [OrderModel.list_product]
  static final list_product = obx.QueryRelationToMany<OrderModel, ProductItem>(
      _entities[0].relations[0]);
}

/// [PriceList] entity fields to define ObjectBox queries.
class PriceList_ {
  /// See [PriceList.uid].
  static final uid =
      obx.QueryIntegerProperty<PriceList>(_entities[1].properties[0]);

  /// See [PriceList.name].
  static final name =
      obx.QueryStringProperty<PriceList>(_entities[1].properties[1]);

  /// See [PriceList.gia_ban].
  static final gia_ban =
      obx.QueryDoubleProperty<PriceList>(_entities[1].properties[2]);

  /// See [PriceList.so_luong].
  static final so_luong =
      obx.QueryIntegerProperty<PriceList>(_entities[1].properties[3]);

  /// See [PriceList.unit].
  static final unit =
      obx.QueryRelationToOne<PriceList, UnitModel>(_entities[1].properties[4]);
}

/// [ProductItem] entity fields to define ObjectBox queries.
class ProductItem_ {
  /// See [ProductItem.uid].
  static final uid =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[0]);

  /// See [ProductItem.uid_product].
  static final uid_product =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[1]);

  /// See [ProductItem.barcode].
  static final barcode =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[2]);

  /// See [ProductItem.ten_san_pham].
  static final ten_san_pham =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[3]);

  /// See [ProductItem.hinh_san_pham].
  static final hinh_san_pham =
      obx.QueryByteVectorProperty<ProductItem>(_entities[2].properties[4]);

  /// See [ProductItem.so_luong].
  static final so_luong =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[5]);

  /// See [ProductItem.supplier].
  static final supplier = obx.QueryRelationToOne<ProductItem, SupplierModel>(
      _entities[2].properties[6]);

  /// See [ProductItem.category].
  static final category = obx.QueryRelationToOne<ProductItem, CategoryModel>(
      _entities[2].properties[7]);

  /// See [ProductItem.unit].
  static final unit = obx.QueryRelationToOne<ProductItem, UnitModel>(
      _entities[2].properties[8]);

  /// See [ProductItem.price].
  static final price = obx.QueryRelationToOne<ProductItem, PriceList>(
      _entities[2].properties[9]);
}

/// [ProductModel] entity fields to define ObjectBox queries.
class ProductModel_ {
  /// See [ProductModel.uid].
  static final uid =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[0]);

  /// See [ProductModel.barcode].
  static final barcode =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[1]);

  /// See [ProductModel.ten_san_pham].
  static final ten_san_pham =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[2]);

  /// See [ProductModel.hinh_san_pham].
  static final hinh_san_pham =
      obx.QueryByteVectorProperty<ProductModel>(_entities[3].properties[3]);

  /// See [ProductModel.ghi_chu].
  static final ghi_chu =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[4]);

  /// See [ProductModel.gia_nhap].
  static final gia_nhap =
      obx.QueryDoubleProperty<ProductModel>(_entities[3].properties[5]);

  /// See [ProductModel.dung_tich].
  static final dung_tich =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[6]);

  /// See [ProductModel.so_luong].
  static final so_luong =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[7]);

  /// See [ProductModel.supplier].
  static final supplier = obx.QueryRelationToOne<ProductModel, SupplierModel>(
      _entities[3].properties[8]);

  /// See [ProductModel.category].
  static final category = obx.QueryRelationToOne<ProductModel, CategoryModel>(
      _entities[3].properties[9]);

  /// See [ProductModel.unit].
  static final unit = obx.QueryRelationToOne<ProductModel, UnitModel>(
      _entities[3].properties[10]);

  /// see [ProductModel.price_list]
  static final price_list = obx.QueryRelationToMany<ProductModel, PriceList>(
      _entities[3].relations[0]);
}

/// [UnitModel] entity fields to define ObjectBox queries.
class UnitModel_ {
  /// See [UnitModel.uid].
  static final uid =
      obx.QueryIntegerProperty<UnitModel>(_entities[4].properties[0]);

  /// See [UnitModel.ten_don_vi].
  static final ten_don_vi =
      obx.QueryStringProperty<UnitModel>(_entities[4].properties[1]);

  /// See [UnitModel.loai_don_vi].
  static final loai_don_vi =
      obx.QueryStringProperty<UnitModel>(_entities[4].properties[2]);

  /// See [UnitModel.ky_hieu].
  static final ky_hieu =
      obx.QueryStringProperty<UnitModel>(_entities[4].properties[3]);
}

/// [CustomerModel] entity fields to define ObjectBox queries.
class CustomerModel_ {
  /// See [CustomerModel.uid].
  static final uid =
      obx.QueryIntegerProperty<CustomerModel>(_entities[5].properties[0]);

  /// See [CustomerModel.ten_khach_hang].
  static final ten_khach_hang =
      obx.QueryStringProperty<CustomerModel>(_entities[5].properties[1]);

  /// See [CustomerModel.hinh_khach_hang].
  static final hinh_khach_hang =
      obx.QueryByteVectorProperty<CustomerModel>(_entities[5].properties[2]);

  /// See [CustomerModel.sdt_khach_hang].
  static final sdt_khach_hang =
      obx.QueryStringProperty<CustomerModel>(_entities[5].properties[3]);

  /// See [CustomerModel.dia_chi].
  static final dia_chi =
      obx.QueryStringProperty<CustomerModel>(_entities[5].properties[4]);

  /// See [CustomerModel.createDate].
  static final createDate =
      obx.QueryDateProperty<CustomerModel>(_entities[5].properties[5]);
}

/// [CategoryModel] entity fields to define ObjectBox queries.
class CategoryModel_ {
  /// See [CategoryModel.uid].
  static final uid =
      obx.QueryIntegerProperty<CategoryModel>(_entities[6].properties[0]);

  /// See [CategoryModel.ten_danh_muc].
  static final ten_danh_muc =
      obx.QueryStringProperty<CategoryModel>(_entities[6].properties[1]);

  /// See [CategoryModel.loai_danh_muc].
  static final loai_danh_muc =
      obx.QueryStringProperty<CategoryModel>(_entities[6].properties[2]);

  /// See [CategoryModel.createDate].
  static final createDate =
      obx.QueryDateProperty<CategoryModel>(_entities[6].properties[3]);
}

/// [SupplierModel] entity fields to define ObjectBox queries.
class SupplierModel_ {
  /// See [SupplierModel.uid].
  static final uid =
      obx.QueryIntegerProperty<SupplierModel>(_entities[7].properties[0]);

  /// See [SupplierModel.name].
  static final name =
      obx.QueryStringProperty<SupplierModel>(_entities[7].properties[1]);

  /// See [SupplierModel.address].
  static final address =
      obx.QueryStringProperty<SupplierModel>(_entities[7].properties[2]);

  /// See [SupplierModel.phone].
  static final phone =
      obx.QueryStringProperty<SupplierModel>(_entities[7].properties[3]);
}
