// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/category_model/category_model.dart';
import 'model/customer_model/customer_model.dart';
import 'model/order_model/order_model.dart';
import 'model/product_model/product_model.dart';
import 'model/unit_model/unit_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8462100601893205612),
      name: 'OrderModel',
      lastPropertyId: const obx_int.IdUid(10, 4944268585478704077),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8479132576122394026),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4523916266304147786),
            name: 'thoi_gian_mua',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3335041921269555226),
            name: 'uid_khach_hang',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1856729103606736230),
            name: 'ten_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2970767064493836545),
            name: 'hinh_khach_hang',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6596033124175339077),
            name: 'sdt_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7967327727288773898),
            name: 'khach_no',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3362299750829196582),
            name: 'tong_tien_no',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 2750023190832166596),
            name: 'tong_gia',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 4944268585478704077),
            name: 'createDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 6117545004750295902),
            name: 'list_product',
            targetId: const obx_int.IdUid(4, 3376631319514457996))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 2774907212245098214),
      name: 'PriceList',
      lastPropertyId: const obx_int.IdUid(8, 8090806262661001619),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1657564179567643833),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7220771278987625304),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6837452732912493970),
            name: 'uid_don_vi',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7032831974186877870),
            name: 'ten_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4266610608789417277),
            name: 'ky_hieu_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6753043266397354163),
            name: 'gia_ban',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1009228909912017167),
            name: 'so_luong',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3376631319514457996),
      name: 'ProductItem',
      lastPropertyId: const obx_int.IdUid(14, 4278042561808483539),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8241860205670702977),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 812030874404062344),
            name: 'uid_product',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8566887608838875456),
            name: 'barcode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7823422843550329682),
            name: 'ten_san_pham',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7405349370863855049),
            name: 'hinh_san_pham',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6931669776031782900),
            name: 'uid_don_vi',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2994713848890333595),
            name: 'ten_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5424488080241102282),
            name: 'ten_loai',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8326155832968762877),
            name: 'ky_hieu_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7410578384373947376),
            name: 'gia_ban_uid_don_vi',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4117038924924385776),
            name: 'gia_ban_ten_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8744451219592071),
            name: 'gia_ban_ky_hieu_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 8312112673082639836),
            name: 'gia_ban',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4278042561808483539),
            name: 'so_luong',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 2699875232035799149),
      name: 'ProductModel',
      lastPropertyId: const obx_int.IdUid(13, 6850306170653725048),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5571371203571454592),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9008781066506134880),
            name: 'barcode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5009954247164826755),
            name: 'ten_san_pham',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6061245436868486034),
            name: 'hinh_san_pham',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7229928441048565709),
            name: 'uid_danh_muc',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1518545134613383641),
            name: 'ten_danh_muc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6982042452188979866),
            name: 'uid_don_vi',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6001654584984488585),
            name: 'ten_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 883625706046727771),
            name: 'ky_hieu_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6021767469518361791),
            name: 'ghi_chu',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6807131810671397937),
            name: 'gia_nhap',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6214602939360826599),
            name: 'dung_tich',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6850306170653725048),
            name: 'so_luong',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 7058649337610862334),
            name: 'price_list',
            targetId: const obx_int.IdUid(3, 2774907212245098214))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 4395494203919008109),
      name: 'UnitModel',
      lastPropertyId: const obx_int.IdUid(5, 7563155607688441043),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5938035661955631924),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3111332530529794604),
            name: 'ten_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8792214140384089297),
            name: 'loai_don_vi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2015183802015280897),
            name: 'ky_hieu',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7563155607688441043),
            name: 'createDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 3646208378886933205),
      name: 'CustomerModel',
      lastPropertyId: const obx_int.IdUid(6, 6050084833291723297),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3579513034822440326),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3157431911059337559),
            name: 'ten_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5664871943150517921),
            name: 'hinh_khach_hang',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7109396362435822095),
            name: 'sdt_khach_hang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9038904169819601270),
            name: 'dia_chi',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6050084833291723297),
            name: 'createDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 3828381250875953042),
      name: 'CategoryModel',
      lastPropertyId: const obx_int.IdUid(4, 5633756422000733903),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2944983431183764254),
            name: 'uid',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6201877116637760197),
            name: 'ten_danh_muc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4835612102365298861),
            name: 'loai_danh_muc',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5633756422000733903),
            name: 'createDate',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(8, 3828381250875953042),
      lastIndexId: const obx_int.IdUid(1, 681671148803372239),
      lastRelationId: const obx_int.IdUid(2, 6117545004750295902),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [4121840046154517435],
      retiredIndexUids: const [681671148803372239],
      retiredPropertyUids: const [
        2554028156081344597,
        3276445162843721571,
        1946115600899689025,
        8241427837389614950,
        8090806262661001619
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    OrderModel: obx_int.EntityDefinition<OrderModel>(
        model: _entities[0],
        toOneRelations: (OrderModel object) => [],
        toManyRelations: (OrderModel object) => {
              obx_int.RelInfo<OrderModel>.toMany(2, object.uid):
                  object.list_product
            },
        getId: (OrderModel object) => object.uid,
        setId: (OrderModel object, int id) {
          object.uid = id;
        },
        objectToFB: (OrderModel object, fb.Builder fbb) {
          final ten_khach_hangOffset = object.ten_khach_hang == null
              ? null
              : fbb.writeString(object.ten_khach_hang!);
          final hinh_khach_hangOffset = object.hinh_khach_hang == null
              ? null
              : fbb.writeListInt8(object.hinh_khach_hang!);
          final sdt_khach_hangOffset = object.sdt_khach_hang == null
              ? null
              : fbb.writeString(object.sdt_khach_hang!);
          fbb.startTable(11);
          fbb.addInt64(0, object.uid);
          fbb.addInt64(1, object.thoi_gian_mua?.millisecondsSinceEpoch);
          fbb.addInt64(2, object.uid_khach_hang);
          fbb.addOffset(3, ten_khach_hangOffset);
          fbb.addOffset(4, hinh_khach_hangOffset);
          fbb.addOffset(5, sdt_khach_hangOffset);
          fbb.addBool(6, object.khach_no);
          fbb.addFloat64(7, object.tong_tien_no);
          fbb.addFloat64(8, object.tong_gia);
          fbb.addInt64(9, object.createDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final thoi_gian_muaValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final thoi_gian_muaParam = thoi_gian_muaValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(thoi_gian_muaValue);
          final uid_khach_hangParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final ten_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final hinh_khach_hangParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 12) as Uint8List?;
          final sdt_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final khach_noParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
          final tong_tien_noParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final tong_giaParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = OrderModel(
              uid: uidParam,
              thoi_gian_mua: thoi_gian_muaParam,
              uid_khach_hang: uid_khach_hangParam,
              ten_khach_hang: ten_khach_hangParam,
              hinh_khach_hang: hinh_khach_hangParam,
              sdt_khach_hang: sdt_khach_hangParam,
              khach_no: khach_noParam,
              tong_tien_no: tong_tien_noParam,
              tong_gia: tong_giaParam,
              createDate: createDateParam);
          obx_int.InternalToManyAccess.setRelInfo<OrderModel>(
              object.list_product,
              store,
              obx_int.RelInfo<OrderModel>.toMany(2, object.uid));
          return object;
        }),
    PriceList: obx_int.EntityDefinition<PriceList>(
        model: _entities[1],
        toOneRelations: (PriceList object) => [],
        toManyRelations: (PriceList object) => {},
        getId: (PriceList object) => object.uid,
        setId: (PriceList object, int id) {
          object.uid = id;
        },
        objectToFB: (PriceList object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final ten_don_viOffset = object.ten_don_vi == null
              ? null
              : fbb.writeString(object.ten_don_vi!);
          final ky_hieu_don_viOffset = object.ky_hieu_don_vi == null
              ? null
              : fbb.writeString(object.ky_hieu_don_vi!);
          fbb.startTable(9);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.uid_don_vi);
          fbb.addOffset(3, ten_don_viOffset);
          fbb.addOffset(4, ky_hieu_don_viOffset);
          fbb.addFloat64(5, object.gia_ban);
          fbb.addInt64(6, object.so_luong);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final uid_don_viParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final ten_don_viParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final ky_hieu_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12);
          final gia_banParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final so_luongParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = PriceList(
              uid: uidParam,
              name: nameParam,
              uid_don_vi: uid_don_viParam,
              ten_don_vi: ten_don_viParam,
              ky_hieu_don_vi: ky_hieu_don_viParam,
              gia_ban: gia_banParam,
              so_luong: so_luongParam);

          return object;
        }),
    ProductItem: obx_int.EntityDefinition<ProductItem>(
        model: _entities[2],
        toOneRelations: (ProductItem object) => [],
        toManyRelations: (ProductItem object) => {},
        getId: (ProductItem object) => object.uid,
        setId: (ProductItem object, int id) {
          object.uid = id;
        },
        objectToFB: (ProductItem object, fb.Builder fbb) {
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final ten_san_phamOffset = object.ten_san_pham == null
              ? null
              : fbb.writeString(object.ten_san_pham!);
          final hinh_san_phamOffset = object.hinh_san_pham == null
              ? null
              : fbb.writeListInt8(object.hinh_san_pham!);
          final ten_don_viOffset = object.ten_don_vi == null
              ? null
              : fbb.writeString(object.ten_don_vi!);
          final ten_loaiOffset = object.ten_loai == null
              ? null
              : fbb.writeString(object.ten_loai!);
          final ky_hieu_don_viOffset = object.ky_hieu_don_vi == null
              ? null
              : fbb.writeString(object.ky_hieu_don_vi!);
          final gia_ban_ten_don_viOffset = object.gia_ban_ten_don_vi == null
              ? null
              : fbb.writeString(object.gia_ban_ten_don_vi!);
          final gia_ban_ky_hieu_don_viOffset =
              object.gia_ban_ky_hieu_don_vi == null
                  ? null
                  : fbb.writeString(object.gia_ban_ky_hieu_don_vi!);
          fbb.startTable(15);
          fbb.addInt64(0, object.uid);
          fbb.addInt64(1, object.uid_product);
          fbb.addOffset(2, barcodeOffset);
          fbb.addOffset(3, ten_san_phamOffset);
          fbb.addOffset(4, hinh_san_phamOffset);
          fbb.addInt64(5, object.uid_don_vi);
          fbb.addOffset(6, ten_don_viOffset);
          fbb.addOffset(7, ten_loaiOffset);
          fbb.addOffset(8, ky_hieu_don_viOffset);
          fbb.addInt64(9, object.gia_ban_uid_don_vi);
          fbb.addOffset(10, gia_ban_ten_don_viOffset);
          fbb.addOffset(11, gia_ban_ky_hieu_don_viOffset);
          fbb.addFloat64(12, object.gia_ban);
          fbb.addInt64(13, object.so_luong);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uid_productParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final ten_san_phamParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final hinh_san_phamParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 12) as Uint8List?;
          final uid_don_viParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final ten_don_viParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final ten_loaiParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final ky_hieu_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final gia_ban_uid_don_viParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final gia_ban_ten_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final gia_ban_ky_hieu_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26);
          final gia_banParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final so_luongParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          final object = ProductItem(
              uid: uidParam,
              uid_product: uid_productParam,
              barcode: barcodeParam,
              ten_san_pham: ten_san_phamParam,
              hinh_san_pham: hinh_san_phamParam,
              uid_don_vi: uid_don_viParam,
              ten_don_vi: ten_don_viParam,
              ten_loai: ten_loaiParam,
              ky_hieu_don_vi: ky_hieu_don_viParam,
              gia_ban_uid_don_vi: gia_ban_uid_don_viParam,
              gia_ban_ten_don_vi: gia_ban_ten_don_viParam,
              gia_ban_ky_hieu_don_vi: gia_ban_ky_hieu_don_viParam,
              gia_ban: gia_banParam,
              so_luong: so_luongParam);

          return object;
        }),
    ProductModel: obx_int.EntityDefinition<ProductModel>(
        model: _entities[3],
        toOneRelations: (ProductModel object) => [],
        toManyRelations: (ProductModel object) => {
              obx_int.RelInfo<ProductModel>.toMany(1, object.uid):
                  object.price_list
            },
        getId: (ProductModel object) => object.uid,
        setId: (ProductModel object, int id) {
          object.uid = id;
        },
        objectToFB: (ProductModel object, fb.Builder fbb) {
          final barcodeOffset =
              object.barcode == null ? null : fbb.writeString(object.barcode!);
          final ten_san_phamOffset = object.ten_san_pham == null
              ? null
              : fbb.writeString(object.ten_san_pham!);
          final hinh_san_phamOffset = object.hinh_san_pham == null
              ? null
              : fbb.writeListInt8(object.hinh_san_pham!);
          final ten_danh_mucOffset = object.ten_danh_muc == null
              ? null
              : fbb.writeString(object.ten_danh_muc!);
          final ten_don_viOffset = object.ten_don_vi == null
              ? null
              : fbb.writeString(object.ten_don_vi!);
          final ky_hieu_don_viOffset = object.ky_hieu_don_vi == null
              ? null
              : fbb.writeString(object.ky_hieu_don_vi!);
          final ghi_chuOffset =
              object.ghi_chu == null ? null : fbb.writeString(object.ghi_chu!);
          fbb.startTable(14);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, barcodeOffset);
          fbb.addOffset(2, ten_san_phamOffset);
          fbb.addOffset(3, hinh_san_phamOffset);
          fbb.addInt64(4, object.uid_danh_muc);
          fbb.addOffset(5, ten_danh_mucOffset);
          fbb.addInt64(6, object.uid_don_vi);
          fbb.addOffset(7, ten_don_viOffset);
          fbb.addOffset(8, ky_hieu_don_viOffset);
          fbb.addOffset(9, ghi_chuOffset);
          fbb.addFloat64(10, object.gia_nhap);
          fbb.addInt64(11, object.dung_tich);
          fbb.addInt64(12, object.so_luong);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final barcodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final ten_san_phamParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final hinh_san_phamParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 10) as Uint8List?;
          final uid_danh_mucParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final ten_danh_mucParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final uid_don_viParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final ten_don_viParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final ky_hieu_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final ghi_chuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 22);
          final gia_nhapParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final dung_tichParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final so_luongParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final object = ProductModel(
              uid: uidParam,
              barcode: barcodeParam,
              ten_san_pham: ten_san_phamParam,
              hinh_san_pham: hinh_san_phamParam,
              uid_danh_muc: uid_danh_mucParam,
              ten_danh_muc: ten_danh_mucParam,
              uid_don_vi: uid_don_viParam,
              ten_don_vi: ten_don_viParam,
              ky_hieu_don_vi: ky_hieu_don_viParam,
              ghi_chu: ghi_chuParam,
              gia_nhap: gia_nhapParam,
              dung_tich: dung_tichParam,
              so_luong: so_luongParam);
          obx_int.InternalToManyAccess.setRelInfo<ProductModel>(
              object.price_list,
              store,
              obx_int.RelInfo<ProductModel>.toMany(1, object.uid));
          return object;
        }),
    UnitModel: obx_int.EntityDefinition<UnitModel>(
        model: _entities[4],
        toOneRelations: (UnitModel object) => [],
        toManyRelations: (UnitModel object) => {},
        getId: (UnitModel object) => object.uid,
        setId: (UnitModel object, int id) {
          object.uid = id;
        },
        objectToFB: (UnitModel object, fb.Builder fbb) {
          final ten_don_viOffset = object.ten_don_vi == null
              ? null
              : fbb.writeString(object.ten_don_vi!);
          final loai_don_viOffset = object.loai_don_vi == null
              ? null
              : fbb.writeString(object.loai_don_vi!);
          final ky_hieuOffset =
              object.ky_hieu == null ? null : fbb.writeString(object.ky_hieu!);
          fbb.startTable(6);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, ten_don_viOffset);
          fbb.addOffset(2, loai_don_viOffset);
          fbb.addOffset(3, ky_hieuOffset);
          fbb.addInt64(4, object.createDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final ten_don_viParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final loai_don_viParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final ky_hieuParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = UnitModel(
              uid: uidParam,
              ten_don_vi: ten_don_viParam,
              loai_don_vi: loai_don_viParam,
              ky_hieu: ky_hieuParam,
              createDate: createDateParam);

          return object;
        }),
    CustomerModel: obx_int.EntityDefinition<CustomerModel>(
        model: _entities[5],
        toOneRelations: (CustomerModel object) => [],
        toManyRelations: (CustomerModel object) => {},
        getId: (CustomerModel object) => object.uid,
        setId: (CustomerModel object, int id) {
          object.uid = id;
        },
        objectToFB: (CustomerModel object, fb.Builder fbb) {
          final ten_khach_hangOffset = object.ten_khach_hang == null
              ? null
              : fbb.writeString(object.ten_khach_hang!);
          final hinh_khach_hangOffset = object.hinh_khach_hang == null
              ? null
              : fbb.writeListInt8(object.hinh_khach_hang!);
          final sdt_khach_hangOffset = object.sdt_khach_hang == null
              ? null
              : fbb.writeString(object.sdt_khach_hang!);
          final dia_chiOffset =
              object.dia_chi == null ? null : fbb.writeString(object.dia_chi!);
          fbb.startTable(7);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, ten_khach_hangOffset);
          fbb.addOffset(2, hinh_khach_hangOffset);
          fbb.addOffset(3, sdt_khach_hangOffset);
          fbb.addOffset(4, dia_chiOffset);
          fbb.addInt64(5, object.createDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final ten_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final hinh_khach_hangParam = const fb.Uint8ListReader(lazy: false)
              .vTableGetNullable(buffer, rootOffset, 8) as Uint8List?;
          final sdt_khach_hangParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final dia_chiParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = CustomerModel(
              uid: uidParam,
              ten_khach_hang: ten_khach_hangParam,
              hinh_khach_hang: hinh_khach_hangParam,
              sdt_khach_hang: sdt_khach_hangParam,
              dia_chi: dia_chiParam,
              createDate: createDateParam);

          return object;
        }),
    CategoryModel: obx_int.EntityDefinition<CategoryModel>(
        model: _entities[6],
        toOneRelations: (CategoryModel object) => [],
        toManyRelations: (CategoryModel object) => {},
        getId: (CategoryModel object) => object.uid,
        setId: (CategoryModel object, int id) {
          object.uid = id;
        },
        objectToFB: (CategoryModel object, fb.Builder fbb) {
          final ten_danh_mucOffset = object.ten_danh_muc == null
              ? null
              : fbb.writeString(object.ten_danh_muc!);
          final loai_danh_mucOffset = object.loai_danh_muc == null
              ? null
              : fbb.writeString(object.loai_danh_muc!);
          fbb.startTable(5);
          fbb.addInt64(0, object.uid);
          fbb.addOffset(1, ten_danh_mucOffset);
          fbb.addOffset(2, loai_danh_mucOffset);
          fbb.addInt64(3, object.createDate?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.uid;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createDateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final uidParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final ten_danh_mucParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final loai_danh_mucParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8);
          final createDateParam = createDateValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createDateValue);
          final object = CategoryModel(
              uid: uidParam,
              ten_danh_muc: ten_danh_mucParam,
              loai_danh_muc: loai_danh_mucParam,
              createDate: createDateParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [OrderModel] entity fields to define ObjectBox queries.
class OrderModel_ {
  /// See [OrderModel.uid].
  static final uid =
      obx.QueryIntegerProperty<OrderModel>(_entities[0].properties[0]);

  /// See [OrderModel.thoi_gian_mua].
  static final thoi_gian_mua =
      obx.QueryDateProperty<OrderModel>(_entities[0].properties[1]);

  /// See [OrderModel.uid_khach_hang].
  static final uid_khach_hang =
      obx.QueryIntegerProperty<OrderModel>(_entities[0].properties[2]);

  /// See [OrderModel.ten_khach_hang].
  static final ten_khach_hang =
      obx.QueryStringProperty<OrderModel>(_entities[0].properties[3]);

  /// See [OrderModel.hinh_khach_hang].
  static final hinh_khach_hang =
      obx.QueryByteVectorProperty<OrderModel>(_entities[0].properties[4]);

  /// See [OrderModel.sdt_khach_hang].
  static final sdt_khach_hang =
      obx.QueryStringProperty<OrderModel>(_entities[0].properties[5]);

  /// See [OrderModel.khach_no].
  static final khach_no =
      obx.QueryBooleanProperty<OrderModel>(_entities[0].properties[6]);

  /// See [OrderModel.tong_tien_no].
  static final tong_tien_no =
      obx.QueryDoubleProperty<OrderModel>(_entities[0].properties[7]);

  /// See [OrderModel.tong_gia].
  static final tong_gia =
      obx.QueryDoubleProperty<OrderModel>(_entities[0].properties[8]);

  /// See [OrderModel.createDate].
  static final createDate =
      obx.QueryDateProperty<OrderModel>(_entities[0].properties[9]);

  /// see [OrderModel.list_product]
  static final list_product = obx.QueryRelationToMany<OrderModel, ProductItem>(
      _entities[0].relations[0]);
}

/// [PriceList] entity fields to define ObjectBox queries.
class PriceList_ {
  /// See [PriceList.uid].
  static final uid =
      obx.QueryIntegerProperty<PriceList>(_entities[1].properties[0]);

  /// See [PriceList.name].
  static final name =
      obx.QueryStringProperty<PriceList>(_entities[1].properties[1]);

  /// See [PriceList.uid_don_vi].
  static final uid_don_vi =
      obx.QueryIntegerProperty<PriceList>(_entities[1].properties[2]);

  /// See [PriceList.ten_don_vi].
  static final ten_don_vi =
      obx.QueryStringProperty<PriceList>(_entities[1].properties[3]);

  /// See [PriceList.ky_hieu_don_vi].
  static final ky_hieu_don_vi =
      obx.QueryStringProperty<PriceList>(_entities[1].properties[4]);

  /// See [PriceList.gia_ban].
  static final gia_ban =
      obx.QueryDoubleProperty<PriceList>(_entities[1].properties[5]);

  /// See [PriceList.so_luong].
  static final so_luong =
      obx.QueryIntegerProperty<PriceList>(_entities[1].properties[6]);
}

/// [ProductItem] entity fields to define ObjectBox queries.
class ProductItem_ {
  /// See [ProductItem.uid].
  static final uid =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[0]);

  /// See [ProductItem.uid_product].
  static final uid_product =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[1]);

  /// See [ProductItem.barcode].
  static final barcode =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[2]);

  /// See [ProductItem.ten_san_pham].
  static final ten_san_pham =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[3]);

  /// See [ProductItem.hinh_san_pham].
  static final hinh_san_pham =
      obx.QueryByteVectorProperty<ProductItem>(_entities[2].properties[4]);

  /// See [ProductItem.uid_don_vi].
  static final uid_don_vi =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[5]);

  /// See [ProductItem.ten_don_vi].
  static final ten_don_vi =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[6]);

  /// See [ProductItem.ten_loai].
  static final ten_loai =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[7]);

  /// See [ProductItem.ky_hieu_don_vi].
  static final ky_hieu_don_vi =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[8]);

  /// See [ProductItem.gia_ban_uid_don_vi].
  static final gia_ban_uid_don_vi =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[9]);

  /// See [ProductItem.gia_ban_ten_don_vi].
  static final gia_ban_ten_don_vi =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[10]);

  /// See [ProductItem.gia_ban_ky_hieu_don_vi].
  static final gia_ban_ky_hieu_don_vi =
      obx.QueryStringProperty<ProductItem>(_entities[2].properties[11]);

  /// See [ProductItem.gia_ban].
  static final gia_ban =
      obx.QueryDoubleProperty<ProductItem>(_entities[2].properties[12]);

  /// See [ProductItem.so_luong].
  static final so_luong =
      obx.QueryIntegerProperty<ProductItem>(_entities[2].properties[13]);
}

/// [ProductModel] entity fields to define ObjectBox queries.
class ProductModel_ {
  /// See [ProductModel.uid].
  static final uid =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[0]);

  /// See [ProductModel.barcode].
  static final barcode =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[1]);

  /// See [ProductModel.ten_san_pham].
  static final ten_san_pham =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[2]);

  /// See [ProductModel.hinh_san_pham].
  static final hinh_san_pham =
      obx.QueryByteVectorProperty<ProductModel>(_entities[3].properties[3]);

  /// See [ProductModel.uid_danh_muc].
  static final uid_danh_muc =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[4]);

  /// See [ProductModel.ten_danh_muc].
  static final ten_danh_muc =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[5]);

  /// See [ProductModel.uid_don_vi].
  static final uid_don_vi =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[6]);

  /// See [ProductModel.ten_don_vi].
  static final ten_don_vi =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[7]);

  /// See [ProductModel.ky_hieu_don_vi].
  static final ky_hieu_don_vi =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[8]);

  /// See [ProductModel.ghi_chu].
  static final ghi_chu =
      obx.QueryStringProperty<ProductModel>(_entities[3].properties[9]);

  /// See [ProductModel.gia_nhap].
  static final gia_nhap =
      obx.QueryDoubleProperty<ProductModel>(_entities[3].properties[10]);

  /// See [ProductModel.dung_tich].
  static final dung_tich =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[11]);

  /// See [ProductModel.so_luong].
  static final so_luong =
      obx.QueryIntegerProperty<ProductModel>(_entities[3].properties[12]);

  /// see [ProductModel.price_list]
  static final price_list = obx.QueryRelationToMany<ProductModel, PriceList>(
      _entities[3].relations[0]);
}

/// [UnitModel] entity fields to define ObjectBox queries.
class UnitModel_ {
  /// See [UnitModel.uid].
  static final uid =
      obx.QueryIntegerProperty<UnitModel>(_entities[4].properties[0]);

  /// See [UnitModel.ten_don_vi].
  static final ten_don_vi =
      obx.QueryStringProperty<UnitModel>(_entities[4].properties[1]);

  /// See [UnitModel.loai_don_vi].
  static final loai_don_vi =
      obx.QueryStringProperty<UnitModel>(_entities[4].properties[2]);

  /// See [UnitModel.ky_hieu].
  static final ky_hieu =
      obx.QueryStringProperty<UnitModel>(_entities[4].properties[3]);

  /// See [UnitModel.createDate].
  static final createDate =
      obx.QueryDateProperty<UnitModel>(_entities[4].properties[4]);
}

/// [CustomerModel] entity fields to define ObjectBox queries.
class CustomerModel_ {
  /// See [CustomerModel.uid].
  static final uid =
      obx.QueryIntegerProperty<CustomerModel>(_entities[5].properties[0]);

  /// See [CustomerModel.ten_khach_hang].
  static final ten_khach_hang =
      obx.QueryStringProperty<CustomerModel>(_entities[5].properties[1]);

  /// See [CustomerModel.hinh_khach_hang].
  static final hinh_khach_hang =
      obx.QueryByteVectorProperty<CustomerModel>(_entities[5].properties[2]);

  /// See [CustomerModel.sdt_khach_hang].
  static final sdt_khach_hang =
      obx.QueryStringProperty<CustomerModel>(_entities[5].properties[3]);

  /// See [CustomerModel.dia_chi].
  static final dia_chi =
      obx.QueryStringProperty<CustomerModel>(_entities[5].properties[4]);

  /// See [CustomerModel.createDate].
  static final createDate =
      obx.QueryDateProperty<CustomerModel>(_entities[5].properties[5]);
}

/// [CategoryModel] entity fields to define ObjectBox queries.
class CategoryModel_ {
  /// See [CategoryModel.uid].
  static final uid =
      obx.QueryIntegerProperty<CategoryModel>(_entities[6].properties[0]);

  /// See [CategoryModel.ten_danh_muc].
  static final ten_danh_muc =
      obx.QueryStringProperty<CategoryModel>(_entities[6].properties[1]);

  /// See [CategoryModel.loai_danh_muc].
  static final loai_danh_muc =
      obx.QueryStringProperty<CategoryModel>(_entities[6].properties[2]);

  /// See [CategoryModel.createDate].
  static final createDate =
      obx.QueryDateProperty<CategoryModel>(_entities[6].properties[3]);
}
